#!/usr/bin/env sh

set -xeo pipefail

# Install one-context
apk add --no-cache one-context e2fsprogs-extra 
apk add --no-cache haveged

# Enable VM contextualization
rc-update add vmcontext default
rc-update add haveged boot

# Add DNS hook in one-context
mkdir -p /usr/local/share/one-context/scripts
cat > /usr/local/share/one-context/scripts/dns-nebula <<'EOF'
#!/bin/sh

. /usr/share/one-context/scripts/utils.sh

dns_servers="$(getval ETH0_DNS)"

echo > /etc/resolv.conf
for nameserver_address in $dns_servers; do
  echo "nameserver $nameserver_address" >> /etc/resolv.conf
done
EOF
chmod +x /usr/local/share/one-context/scripts/dns-nebula
ln -s /usr/local/share/one-context/scripts/dns-nebula /etc/one-context.d/01-dns-nebula

# Reset network interfaces
cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback
# BEGIN generated by /usr/share/one-context/scripts/network
# Do not modify this block, any modifications will be lost after reboot!
auto eth0
iface eth0 inet dhcp
# END generated
EOF

# Disable resolv.conf overwriting
mkdir -p /etc/udhcpc
echo 'RESOLV_CONF=NO' >> /etc/udhcpc/udhcpc.conf

sync
